test

diff --git a/.github/workflows/Build-SukiSU.yml b/.github/workflows/Build-SukiSU.yml
--- a/.github/workflows/Build-SukiSU.yml
+++ b/.github/workflows/Build-SukiSU.yml
@@ -209,9 +209,13 @@ jobs:
           cp -r ../SukiSU_patch/other/zram/lz4k/crypto/* ./common/crypto
           cp -r ../SukiSU_patch/other/zram/lz4k_oplus ./common/lib/
           fi
-
           cd ./common
-          patch -p1 < 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch || true
+          patch -p1 < 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch
+          if [ $? -ne 0 ]; then
+            echo "ERROR: SUSFS patch failed to apply completely"
+            cat fs/proc/base.c.rej
+            exit 1
+          fi
           echo "完成"
 
       - name: Apply Hide Stuff Patches
